### ISSUE TITLE
Possibility to use keys from a Nitrokey HSM

### ISSUE THREAD

**Issue by CMon** [Nitrokey/nethsm#10]
Is there a possibility to use keys that are stored on a Nitrokey HSM? 

If not are there plans to either support an import (via a existing dkek and exported keys from an existing Nitrokey HSM) or perhaps by plugging in the Nitrokey HSM into one of the USB ports?

I understand that if we would use keys directly from the usb would result into a loss of speed.

**Comment by jans23** [comment]
No, we don't plan any key exchange between these models.
