### ISSUE TITLE
(Feature Request) Support for AES ECB

### ISSUE THREAD

**Issue by aio-witc** [Nitrokey/nethsm#2]
Direct AES ECB encryption should be supported, only a single 128b block would be sufficent. (should possibly limited to a single block to avoid unsecure misunderstandings...)

Usecase: To encrypt/decrypt session keys, protect "custom" protocols with the hsm.

Priority: Medium, mid-term

**Comment by jans23** [comment]
You know we do offer AES-CBC which is often preferable over ECB. This is also why we chose CBC in the first place. Please elaborate, in which specific use case do you need ECB and why would CBC not be sufficient?

**Comment by jans23** [comment]
With CBC the IV is XORed with the plaintext block, so a zero IV leaves it untouched, and makes it identical to a single ECB block encryption.

For completeness: The only practical difference would be, that you can’t send a whole file to NetHSM and let it ECB encrypted. Instead you would need to send each block in a separate requests with IV=0 to „implement“ ECB with NetHSM. But you wrote that you don't want to do so (and you shouldn't!).

So I don't see a need for a dedicated ECB operation.
