### ISSUE TITLE
Problems with NetHSM credentials

### ISSUE THREAD

**Issue by esdrasspd** [Nitrokey/nethsm#4]
Hello, it is a pleasure to be able to greet you through this medium.

I have problems when using NetHSM, since when making the "provision" state and placing the admin and password in other endpoints does not accept it. Could you please help us?

**Comment by esdrasspd** [comment]
@linse @mato @hannesm @dinosaure @robin-nitrokey

**Comment by robin-nitrokey** [comment]
Hi @esdrasspd, can you please share some more details on how you are provisioning the device?  Are you using the testing container, the demo instance or a proper NetHSM device?  What command do you use to provision the NetHSM and what is the output?

**Comment by esdrasspd** [comment]
> Hi @esdrasspd, can you please share some more details on how you are provisioning the device? Are you using the testing container, the demo instance or a proper NetHSM device? What command do you use to provision the NetHSM and what is the output?

Hi @robin-nitrokey 

I am using a Docker container which has the NetHSM API instance, I just got it from this link: https://hub.docker.com/r/nitrokey/nethsm/ First raise the container on port 8443, then run the command "nitropy nethsm --host localhost:8443 --no-verify-tls provision" and I put the credentials admin passphrase: Administrator and unlock passpharse: unlockunock and it is placed in operational state without problem, but when I want to execute commands that require authentication for example "nitropy nethsm --host localhost:8443 --no-verify-tls get-config --network", it asks me for credentials and I enter the ones I placed in the provision (administrator and unlockunlock). And when entering the credentials I get an Unauthorized error.

I don't know if I'm doing something wrong, I would like you to help me please, greetings.

**Comment by robin-nitrokey** [comment]
Ah, I see.  During provisioning, you enter the admin passphrase and the unlock passphrase.  The user name for the admin user is always admin.  So when e. g. `get-config` prompts for the user name and passphrase, you need to enter `admin` and, in your case, `administrator`.  Then it should work.

**Comment by esdrasspd** [comment]
That's it, it worked for me, thank you very much brother for your time
